REST Messaging System
CenterForDigitalHumanities/rerum_server_nodejs pull request #23
Opened 2022-02-24 20:50 UTC by thehabes

Created a messenger in the rest.js module.

I added the rest.messenger() function as the middleware for error handling (in app.js).  If something happens to not be handled in the messenger, it will fail out to a generic 500 with generic message.  I did not find a way to trigger this behavior, but someone will some day.

try-catch in the db-controller was useless.  Express handling takes precedence, which is why those all went way.  They were never reached; it always fails to the error handler (now `rest.messenger`), never the catch().  See the code documentation, it is insightful.

Tested and working.

2022-02-24 22:22 UTC, cubap requested changes
This is heroic. I made some notes that we can talk about tomorrow. I do not have any concerns, just want to be on the same page.

2022-02-24 22:22 UTC, cubap commented on app.js
> +const rest = require('./rest.js')
oops. This is in here twice. `rest_messenger` above could maybe get removed.

2022-02-24 22:22 UTC, cubap commented on app.js
> +  res.status(500).send('Something broke!')
Maybe this should be the teapot error, since we can't exactly claim the server is broken if we make it this far ;)

2022-02-24 22:22 UTC, cubap commented on db-controller.js
> +        //Can I set the 400 status here?
The response.status is passed to next() so it should work. This is definitely a 400 state.

2022-02-24 22:22 UTC, cubap commented on rest.js
> +    const responseCode = err.statusCode
Instead of `sendStatus(401)` and the like above, could we `.send()` or `.json()` on success and just set the status code at the end of the controllers to manage everything here? We could perhaps set the status text as well to add custom messages?

2022-02-24 22:22 UTC, cubap commented on rest.js
> +    customResponseBody.message = responseMessage
You overwrite this almost right away, but it is more likely to be correct.

2022-02-24 22:22 UTC, cubap commented on routes/api-routes.js
> + * TODO If there is nothing to PATCH, return a 204 saying as much (this is a warning)
These would not be `no content` but perhaps `not modified`. I would rather get a 200 back on a PATCH that succeeded but had no effect than a 204 warning. I'm open, of course to a RESTful rebuttal.

2022-02-25 00:14 UTC, thehabes commented on app.js
> +  res.status(500).send('Something broke!')
Sure, it's a fail safe and that's all.  Whatever we want.  As long as the status is 500.

2022-02-25 00:18 UTC, thehabes commented on db-controller.js
> +        //Can I set the 400 status here?
o yeah I missed this one.  Nothing flags here as 400 unless we force it to because nothing is bad about a JSON object that doesn't have the `@id` key to the http module.  So if we want to fail out to the error handler, we do res.status(400) and let it go.  Might have to be better with the error handler because it will overwrite the error message about the `@id` for the 400 code message.

2022-02-25 00:27 UTC, thehabes commented on rest.js
> +    const responseCode = err.statusCode
Not sure, I don't see what you mean.  You will have to share screen.

2022-02-25 00:31 UTC, thehabes commented on routes/api-routes.js
> + * TODO If there is nothing to PATCH, return a 204 saying as much (this is a warning)
Yeah this is a funky one.  We went with 204 in the Java.
204 doesn't necessarily reflect much about the object on the server, it means there's no content to return.  It was our way of implementing an 'OK Warning'.  If you just want an OK, 200 is probably better.  REST doesn't actual dictate that you detect the hit or miss here as far as "there is at least one property to change".  As far as it goes, either 20X would be fair game.

3XX (Not Modified) family implies "redirection", so best not to go there.  Let's stick with the 200 family.

2022-02-25 00:38 UTC, thehabes commented on app.js
> +const rest = require('./rest.js')
Yeah, rest_messenger should go, I though about tryin something like `const rest_messenger=require('./rest.js').messenger()` but did not.

2022-02-25 00:39 UTC, thehabes commented on app.js
> +const rest_messenger = require("./rest.js")
Sure, once we have a working proof we can do a restructuring on main

2022-02-25 00:42 UTC, thehabes commented on rest.js
> +    customResponseBody.message = responseMessage
I went back and forth about whether to establish it right away and `+=` to it.  Obviously I went with overwrite it for any case we handle, but that may not best.  It doesn't let us pass in a specific `400 cuz your JSON body for this update didn't have an id!` message, for example.

2022-02-25 16:18 UTC, cubap approved these changes

2022-02-25 16:24 UTC, thehabes commented
We will end the sprint with a retrospective on this PR.  Focus in on code clean up and documentation.  Do the 204 -> 200 change and try to feed into the rest.messenger() instead of `res.status(4XX).send("A message the messenger should be sending")`.

2022-02-28 18:42 UTC, merged